services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: carrier-sales-db
    environment:
      POSTGRES_USER: carrier_user
      POSTGRES_PASSWORD: carrier_password_123
      POSTGRES_DB: carrier_sales
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - carrier-network

  # Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carrier-sales-api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - API_KEY=${API_KEY}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - carrier-network


volumes:
  postgres_data:
    driver: local

networks:
  carrier-network:
    driver: bridge